### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Rafinha29** [Makuna/Rfid134#6]
I tried to compile the example provided for software serial and gives me error.

**Comment by Makuna** [comment]
I need more information.
What platform?  
What versions (of Arduino, of Platform board support of the RFID library)
What was the compile error?

**Comment by Rafinha29** [comment]
I'm on windows 10 Arduino 1.8.12 (Windows Store 1.8.33.0) Library Rfid134 version 1.0.1 with an arduino UNO, I just uncommented the two lines for softwareserial and comment the hardwareserial one, here the error: 
Arduino:1.8.12 (Windows Store 1.8.33.0) (Windows 10), Tarjeta:"Arduino Uno"

In file included from C:\Users\Rafa29\AppData\Local\Temp\arduino_modified_sketch_36747\ReadRfid.ino:3:0:

C:\Users\Rafa29\Documents\Arduino\libraries\Rfid134_by_Makuna\src/Rfid134.h: In instantiation of 'void Rfid134<T_SERIAL_METHOD, T_NOTIFICATION_METHOD>::begin() [with T_SERIAL_METHOD = SoftwareSerial; T_NOTIFICATION_METHOD = RfidNotify]':

C:\Users\Rafa29\AppData\Local\Temp\arduino_modified_sketch_36747\ReadRfid.ino:69:14:   required from here

C:\Users\Rafa29\Documents\Arduino\libraries\Rfid134_by_Makuna\src/Rfid134.h:59:9: error: no matching function for call to 'SoftwareSerial::begin(int, int)'

         _serial.begin(9600, SERIAL_8N2);

         ^~~~~~~

In file included from C:\Users\Rafa29\AppData\Local\Temp\arduino_modified_sketch_36747\ReadRfid.ino:2:0:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\SoftwareSerial\src/SoftwareSerial.h:94:8: note: candidate: void SoftwareSerial::begin(long int)

   void begin(long speed);

        ^~~~~

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\SoftwareSerial\src/SoftwareSerial.h:94:8: note:   candidate expects 1 argument, 2 provided

exit status 1
Error compilando para la tarjeta Arduino Uno.

**Comment by Makuna** [comment]
https://github.com/Makuna/Rfid134/pull/7

**Comment by Makuna** [comment]
https://github.com/Makuna/Rfid134/releases/tag/1.0.2

See the updated example
