### ISSUE TITLE
WL134 and ESP8266

### ISSUE THREAD

**Issue by hagelric** [Makuna/Rfid134#9]
Sometime  WL134 module doesn't "read" (blue LED turns on, but no reading). After some seconds, wl134 reads and transmit correctly. Why?

**Comment by Makuna** [comment]
To be clear,  are you stating there is a delay from the LED to receiving a packet or are you stating that some times a packet is never received?

BTW, this is a question, and as by the guidelines outlined when you created this issue, this is not the place to ask questions, it will be closed soon.  Please go to the Gitter channel to ask questions as the issues area is for tracking bugs.

**Comment by hagelric** [comment]
Sorry about asks here, i don't know gitter and I didn't find any reference about wl134 there.
I'm using softwareserial (because esp8266 has only 2 UARTS, but UART1 has only TX in the board, so it useless to receive wl134 data). The problem is "sometimes a packet never received". I use a tag a couple of times and LED works ok, but nothing is readed in serial port... so I wait 10sec and reading starts again - and I can read a few times. But if I wait the data communication stops again (randomly).
